version: "3.8"

services:
  client:
    build: ./node-app
    command: sh -c "npm install && npm start"
    volumes:
      - ./node-app:/app/node-app
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - postgresdb
    env_file:
      - ./node-app/.env
    environment:
      - DB_HOST=postgresdb

  server:
    build: ./tutor
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./tutor:/app/tutor
    ports:
      - 8000:8000
    networks:
      - app-network
    env_file:
      - ./tutor/.env

  postgresdb:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file: ./node-app/.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d thabo-chatbot-db"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:

networks:
  app-network:
