version: "3.8"

services:
  node-server:
    build: ./nodejs-integrator
    volumes:
      - ./nodejs-integrator:/app/nodejs-integrator
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - postgresdb
    env_file:
      - ~/secrets/node-env
    environment:
      - DB_HOST=postgresdb

  fastapi-server:
    build: ./fastapi-tutor
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 6"
    volumes:
      - ./fastapi-tutor:/app/fastapi-tutor
    ports:
      - 8000:8000
    networks:
      - app-network
    env_file:
      - ~/secrets/fast-env

  react-server:
    build: ./react-admin-app
    volumes:
      - ./react-admin-app:/react-admin-app
    ports:
      - 3001:3001
    networks:
      - app-network
    env_file:
      - ~/secrets/react-env

  postgresdb:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file: ~/secrets/node-env
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d thabo-chatbot-db"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:

networks:
  app-network:
